#!/usr/bin/env python3
"""install_units.py -- render and install the native systemd units from systemd/*.service
templates plus a per-host profile.

    python src/scripts/install_units.py --profile deploy/host.yaml             # dry run: diff
    sudo python src/scripts/install_units.py --profile deploy/host.yaml --apply [--enable] [--restart]
    sudo python src/scripts/install_units.py --profile deploy/host.yaml --apply --extract-env soc.service

Profile (YAML, tracked in the deployment repo, no secrets):

    root: /opt/ids_product                  # checkout (WorkingDirectory, paths)
    python: /opt/ids_product/venv/bin/python3
    user: ids
    group: ids
    env_file: /etc/ids_product/ids.env      # secrets, KEY=value, mode 0600
    units:                                  # which templates to install, and host additions
      soc.service:
        Service:
          SupplementaryGroups: zeek
      soc-scheduler.service:
        Service:
          ReadWritePaths: /opt/zeek/logs

Host additions are written as a drop-in <unit>.d/10-host.conf, so the rendered unit stays
identical to the template. --extract-env (one time, when moving off units that carried secrets
as Environment= lines): copies those lines from the INSTALLED unit into env_file (0600,
root-owned, missing keys only) before the unit is replaced. Diffs never print Environment=
values. Backups of replaced files go to /var/backups/ids-units/<timestamp>/.
"""
import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
PLACEHOLDER_RE = re.compile(r"@([A-Z_]+)@")
BACKUP_ROOT = Path("/var/backups/ids-units")
DROPIN_NAME = "10-host.conf"


def render_template(text: str, profile: dict) -> str:
    values = {
        "ROOT": profile["root"],
        "PYTHON": profile["python"],
        "USER": profile["user"],
        "GROUP": profile.get("group", profile["user"]),
        "ENV_FILE": profile["env_file"],
    }
    out = PLACEHOLDER_RE.sub(lambda m: str(values[m.group(1)]) if m.group(1) in values else m.group(0), text)
    left = sorted(set(PLACEHOLDER_RE.findall(out)))
    if left:
        raise ValueError(f"unknown placeholder(s) in template: {', '.join(left)}")
    return out


def render_dropin(sections: dict) -> str:
    """{Section: {Directive: value | [values]}} -> drop-in text. A list becomes repeated lines."""
    if not sections:
        return ""
    lines = ["# Generated by src/scripts/install_units.py from the host profile -- do not edit.\n"]
    for section, directives in sections.items():
        lines.append(f"\n[{section}]\n")
        for key, value in (directives or {}).items():
            for v in (value if isinstance(value, list) else [value]):
                if isinstance(v, bool):
                    v = "true" if v else "false"
                lines.append(f"{key}={v}\n")
    return "".join(lines)


def redact(text: str) -> str:
    return re.sub(r"(?m)^(\s*Environment=)(?!IDS_SCHEDULER_STANDALONE=)[^\n]*$", r"\1<redacted>", text)


def plan(profile: dict, templates: Path, dest: Path) -> list:
    """[(target path, new text)] for every unit and drop-in the profile asks for."""
    out = []
    for unit, sections in (profile.get("units") or {}).items():
        tpl = templates / unit
        if not tpl.exists():
            raise ValueError(f"no template for {unit} in {templates}")
        out.append((dest / unit, render_template(tpl.read_text(encoding="utf-8"), profile)))
        dropin = render_dropin(sections or {})
        dropin_path = dest / f"{unit}.d" / DROPIN_NAME
        if dropin or dropin_path.exists():
            out.append((dropin_path, dropin))  # empty text = remove a stale drop-in
    return out


def extract_env(installed_unit: Path, env_file: Path) -> list:
    """Moves Environment=KEY=VALUE lines of an installed unit into env_file (missing keys only).
    Returns the keys added (never their values)."""
    pairs = []
    for line in installed_unit.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\s*Environment=(.*)$", line)
        if not m:
            continue
        raw = m.group(1).strip()
        if raw.startswith('"') and raw.endswith('"'):
            raw = raw[1:-1]
        if "=" in raw:
            key, value = raw.split("=", 1)
            if key != "IDS_SCHEDULER_STANDALONE":
                pairs.append((key.strip(), value))
    existing = set()
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                existing.add(line.split("=", 1)[0].strip())
    added = [(k, v) for k, v in pairs if k not in existing]
    if added:
        env_file.parent.mkdir(parents=True, exist_ok=True)
        old = env_file.read_text(encoding="utf-8") if env_file.exists() else ""
        if old and not old.endswith("\n"):
            old += "\n"
        new = old + "".join(f"{k}={v}\n" for k, v in added)
        tmp = env_file.with_name(env_file.name + ".tmp")
        fd = os.open(str(tmp), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(new)
        os.chmod(tmp, 0o600)
        os.replace(tmp, env_file)
    return [k for k, _ in added]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile", required=True)
    ap.add_argument("--templates", default=str(ROOT / "systemd"))
    ap.add_argument("--dest", default="/etc/systemd/system")
    ap.add_argument("--apply", action="store_true", help="install (needs root); default: dry run")
    ap.add_argument("--extract-env", metavar="UNIT", action="append", default=[],
                    help="first move this installed unit's Environment= lines into env_file")
    ap.add_argument("--enable", action="store_true", help="systemctl enable the profile's units")
    ap.add_argument("--restart", action="store_true", help="restart the profile's units, in profile order")
    a = ap.parse_args(argv)

    profile = yaml.safe_load(Path(a.profile).read_text(encoding="utf-8")) or {}
    for key in ("root", "python", "user", "env_file", "units"):
        if not profile.get(key):
            print(f"profile is missing '{key}'", file=sys.stderr)
            return 2
    dest = Path(a.dest)
    try:
        items = plan(profile, Path(a.templates), dest)
    except ValueError as exc:
        print(f"REFUSING: {exc}", file=sys.stderr)
        return 2

    changed = []
    for path, text in items:
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        if old == text:
            print(f"unchanged  {path}")
            continue
        changed.append((path, text))
        verb = "remove" if not text else ("update" if old else "create")
        print(f"{verb:9}  {path}")
        for line in difflib.unified_diff(redact(old).splitlines(), redact(text).splitlines(),
                                         fromfile=f"{path} (installed)", tofile=f"{path} (new)", lineterm=""):
            print("    " + line)
    for unit in a.extract_env:
        print(f"extract   Environment= lines of {dest / unit} -> {profile['env_file']} (values not shown)")

    if not a.apply:
        print("Dry run only. Re-run as root with --apply to install.")
        return 0
    if hasattr(os, "geteuid") and os.geteuid() != 0:
        print("--apply needs root (sudo).", file=sys.stderr)
        return 2

    for unit in a.extract_env:
        added = extract_env(dest / unit, Path(profile["env_file"]))
        print(f"env_file: added {len(added)} key(s): {', '.join(added) or '-'}")

    stamp = time.strftime("%Y%m%d-%H%M%S")
    for path, text in changed:
        if path.exists():
            # Old units may carry secrets (Environment= lines): root-only backup.
            backup = BACKUP_ROOT / stamp / path.relative_to(dest)
            backup.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
            for d in (BACKUP_ROOT, BACKUP_ROOT / stamp, backup.parent):
                os.chmod(d, 0o700)
            shutil.copy2(path, backup)
            os.chmod(backup, 0o600)
        if not text:
            path.unlink()
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(f".{path.name}.tmp")
        tmp.write_text(text, encoding="utf-8")
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    if changed:
        print(f"backups: {BACKUP_ROOT / stamp}")
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    units = list(profile["units"])
    if a.enable:
        subprocess.run(["systemctl", "enable", *units], check=True)
    if a.restart:
        for unit in units:
            subprocess.run(["systemctl", "restart", unit], check=True)
            print(f"restarted {unit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
